### ISSUE TITLE
Android TV [FEATURE]

### ISSUE THREAD

**Issue by MOD-PROD** [Pato05/uploadgram-app#7]
Hello, I installed this nice application on Android TV, unfortunately it is impossible to select the buttons with the remote control. Could you add remote control support please? 

![Uploadgram_480x270](https://user-images.githubusercontent.com/62851595/117173283-e8775380-adcc-11eb-8e53-e01c8e134bd4.png)

Thanks

**Comment by Pato05** [comment]
I guess this is possible. I'll try to improve this behaviour in the next releases of the app.

**Comment by Pato05** [comment]
As of now, I've decided this won't get fixed, because the application doesn't really target Android TV devices. Plus, you should be able to find a button on your remote that switches to a "mouse" mode, with which you should be able to click everything.

Though, if anyone wants to make a pull request adding this, it is more than welcome here!
